---
- name: HTTPD. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present
  become: yes
  tags:
    web
 
- name: HTTPD. Remove welcome
  file:
    path: "/etc/httpd/conf.d/welcome.conf"
    state: absent
  become: yes
  tags:
    web

- name: HTTPD. Enable and start service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
  tags:
    web
